name: webapp-${ENVIRONMENT}
services:
  app:
    build:
      context: ./workspaces/app
      target: ${ENVIRONMENT}
    container_name: app-${ENVIRONMENT}
    environment:
      NODE_ENV: ${ENVIRONMENT}
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db:5432/database
      ASTRO_TELEMETRY_DISABLED: 1
    volumes:
      - ./workspaces/app:/app
      - nodemodules:/app/node_modules
    ports:
      - "80:4321"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  worker:
    build: ./workspaces/worker
    container_name: worker-${ENVIRONMENT}
    environment:
      NODE_ENV: ${ENVIRONMENT}
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db:5432/database
    volumes:
      - ./workspaces/worker:/worker
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    build:
      context: ./workspaces/db
    container_name: db-${ENVIRONMENT}
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 30
    restart: unless-stopped
volumes:
  pgdata:
    name: db-pgdata-${ENVIRONMENT}
  nodemodules:
    name: app-nodemodules-${ENVIRONMENT}
